default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'liponaldo7' %>
  host: localhost

development:
  <<: *default
  database: miami_waiter_training_backend_development

test:
  <<: *default
  database: miami_waiter_training_backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
