default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  host: localhost

development:
  <<: *default
  database: miami_waiter_training_backend_development

test:
  <<: *default
  database: miami_waiter_training_backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
